map_type: costmap

obstacle_range: 4.0
raytrace_range: 5.0

transform_tolerance: 1.0

#observation_sources: laser_scan_sensor

#laser_scan_sensor: {
#  sensor_frame: hokuyo,
#  data_type: LaserScan,
#  topic: /udacity_bot/laser/scan,
#  marking: true,
#  clearing: true
#}
